config/routes.rb
BSG::Application.routes.draw do 

  resources :blogposts

  root to: 'static_pages#home'

  match '/about/company-info', to: 'static_pages#about_company_info'

  match '/our-work/a-game-of-zolf', to: 'static_pages#our_work_a_game_of_zolf'

  match '/our-work/misfortune-cookie-box', to: 'static_pages#our_work_misfortune_cookie_box'

  match '/our-work/app-development', to: 'static_pages#our_work_app_development'

  match '/contact-success', to: 'static_pages#contact_success'

  match 'contact', to: 'contact#new', :as => 'contact', :via => :get
  match 'contact', to: 'contact#create', :as => 'contact', :via => :post

  match '/blog', to: 'blogposts#index'

  match '/blog-admin', to: 'blogposts#admin_index'

  match  'archive/:year(/:month(/:day))' => 'archives#monthly_index', :constraints => { :year => /\d{4}/, :month => /\d{2}/, :day => /\d{2}/ }

 

end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
  attr_accessible :content, :title

  validates :title, :presence => true
  validates :content, :presence => true

  def to_param
  	"#{id} #{title}".parameterize
  end

#  def to_param
#    title
#  end
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :firstname,:lastname, :email, :company, :phone, :body

  validates_presence_of :firstname, :message => "Please enter your first name"
  validates_presence_of :lastname, :message => "Please enter your last name"
  validates_presence_of :email, :message => "Please enter your email address"
  validates_presence_of :body, :message => "You didn't leave a message"
  validates :email, :format => { :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, :message => "The e-mail address you entered is invalid" }, :allow_blank => true 

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @blogpost_by_month = Blogpost.find(:all, :order => "created_at DESC").group_by { |post| post.created_at.beginning_of_month }
  end

  def monthly_index #blog archive
    @year = params[:year]
    @month = params[:month]
    @day = params[:day]
    @date = [@year,"/",@month].join("")
    @start_date = Time.parse(@date).beginning_of_month
    @end_date = Time.parse(@date).end_of_month
    @blogpost_array = Blogpost.where(:created_at => @start_date..@end_date).paginate(page: params[:page], :per_page => 5, :order => "created_at DESC")
    @blogpost_by_month = Blogpost.find(:all, :order => "created_at DESC").group_by { |post| post.created_at.beginning_of_month }
#	@blogpost = Blogpost.where(:created_at => (Time.now.midnight - 10.day)..Time.now.midnight)
  end
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController

  http_basic_authenticate_with :name => "bearshotgun", :password => "bearsrul3", :except => [:index, :show]

  # GET /blogposts
  # GET /blogposts.json
  def index
    @blogposts = Blogpost.paginate(page: params[:page], :per_page => 5, :order => "created_at DESC")
    @blogpost_by_month = Blogpost.find(:all, :order => "created_at DESC").group_by { |post| post.created_at.beginning_of_month }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogposts }
    end
  end

  def admin_index
    @blogposts = Blogpost.all(:order => "created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogposts }
    end
  end

  # GET /blogposts/1
  # GET /blogposts/1.json
  def show
    @blogpost = Blogpost.find(params[:id])
    @blogpost_by_month = Blogpost.find(:all, :order => "created_at DESC").group_by { |post| post.created_at.beginning_of_month }

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blogpost }
    end
  end

  # GET /blogposts/new
  # GET /blogposts/new.json
  def new
    @blogpost = Blogpost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blogpost }
    end
  end

  # GET /blogposts/1/edit
  def edit
    @blogpost = Blogpost.find(params[:id])
  end

  # POST /blogposts
  # POST /blogposts.json
  def create
    @blogpost = Blogpost.new(params[:blogpost])

    respond_to do |format|
      if @blogpost.save
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully created.' }
        format.json { render json: @blogpost, status: :created, location: @blogpost }
      else
        format.html { render action: "new" }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogposts/1
  # PUT /blogposts/1.json
  def update
    @blogpost = Blogpost.find(params[:id])

    respond_to do |format|
      if @blogpost.update_attributes(params[:blogpost])
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogposts/1
  # DELETE /blogposts/1.json
  def destroy
    @blogpost = Blogpost.find(params[:id])
    @blogpost.destroy

    respond_to do |format|
      format.html { redirect_to blogposts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create #check contact form
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to '/contact-success'
    else
#      flash[:notice]= "Please fill in all required(*) fields."
#      redirect_to '/contact'
    render action: "new" 
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @latestpost = Blogpost.order("created_at").last
  end

  def about_company_info
  end

  def our_work_a_game_of_zolf
  end

  def our_work_misfortune_cookie_box
  end

  def our_work_app_development
  end

  def contact_success
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end


def dat_markdown(text) #keeps formatting
  options = {
    :autolink => true,
    :space_after_headers => true,
    :no_intra_emphasis => true
  }
  markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, options)
  markdown.render(text).html_safe
end

def sentence_truncate(s, options = {}) #display x amount of sentences
	options.reverse_merge!({:words => 0})
    if options[:sentences]
      return s.split(/\.(\s|$)+/)[0, options[:sentences]].map{|s| s.strip}.join('. ') + '.'
    end
  a = s.split(/\s/) # or /[ ]+/ to only split on spaces
  n = options[:words]
  a[0...n].join(' ') + (a.size > n ? '...' : '')
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pagination_helper.rb
module PaginationHelper #custom pagination
    class LinkRenderer < WillPaginate::ActionView::LinkRenderer
        
    protected

      def page_number(page)
        unless page == current_page
          link(page, page, :rel => rel_value(page))
        else
          link(page, "#", :class => 'active')
        end
      end

      def gap
        text = @template.will_paginate_translate(:page_gap) { '&hellip;' }
        %(<li class="disabled"><a>#{text}</a></li>)
      end

      def next_page
        num = @collection.current_page < @collection.total_pages && @collection.current_page + 1
        previous_or_next_page(num, @options[:next_label], 'next')
      end

      def previous_or_next_page(page, text, classname)
        if page
          link(text, page, :class => classname)
        else
          link(text, "#", :class => classname + ' disabled')
        end
      end

      def html_container(html)
        tag(:div, tag(:ul, html), container_attributes)
      end

    private

        def link(text, target, attributes = {})
        if target.is_a? Fixnum
          attributes[:rel] = rel_value(target)
          target = url(target)
        end

                unless target == "#"
                    attributes[:href] = target
                end

        classname = attributes[:class]
        attributes.delete(:classname)
        tag(:li, tag(:a, text, attributes), :class => classname)
        end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/archives/index.html.erb
<div class="archives">
    <h2>Blog Archive</h2>

    <% @blogpost_by_day.sort.reverse.each do |day, blogposts| %>
    <h3><%= day.strftime("%d %B %Y") %></h3>
    <table>
      <% for blogpost in blogposts %>
        <tr>
        	<td><%= link_to blogpost.title, blogpost_path(blogpost) %></td>
        	<td><%= dat_markdown sentence_truncate(blogpost.content, :sentences => 1) %></td>
        	<td><%= blogpost.created_at.strftime("%d %b. %Y %H:%M") %></td>
      <% end %>
    </table>
    <% end %>

<pre>
  <%= @blogpost_by_day.inspect %>
</pre>
</div>

app/views/archives/monthly_index.html.erb
<% provide(:title, 'Archive') %>
<div id="header_container">
     <div id="wrapper">
        <div id="header">

          <div id="logo">
            <%= link_to image_tag("bear-archery-products-logo.gif", id:"logo", alt:"Bearshotgun"), '/' %>
          </div>
            <ul id="nav">
              <li><a class="upper" href="/blog"><span style="color: #DA5252;">News</span></a></li>
              <li><a class="upper" href="/our-work/a-game-of-zolf">Our Work</a>
            </li>
              <li><a class="upper" href="/about/company-info">About us</a>
            </li>
              <li><a class="upper" href="/contact">Contact</a></li>
            </ul>

<%= render 'layouts/subpageheader' %>

<div id= "wrapper">
  <div id= "body_container" style="height: auto; float: left;">
    <div style="margin-top:-240px;">
      <img src="/assets/Rovio_subpagebanner_6.jpg" alt:"Welcome to Bearshotgun!" style="border-top-left-radius: 15px; border-top-right-radius: 15px; width: 980px; height: 240px;" />
    </div>
    <div id="subpagepicbox" style="margin-left: 140px; width: 103px;">
    </div>
    <img id="subpagepic" style="margin-left: 140px;" src="/assets/News.png" alt:"News" /> 

    <div>
      <div id="container-outer">
        <div id="container-inner">

        <div id="blog_archive">
          <div id="archive_box">
            <% @blogpost_by_month.sort.reverse.each do |date, blogposts| %>
            <p class="blog_year"><%= date.strftime("%Y") %></p>
            
            <table>
              <tr>
                <td><a style="text-decoration: none; outline: none;" href="<%= ["/archive/",date.strftime("%Y"),"/",date.strftime("%m")].join %>"><p class="blog_month"><%= date.strftime("%B") %></p></a></td><td class="blog_amount"><%= link_to [("("),blogposts.count,(")")].join, ["/archive/",date.strftime("%Y"),"/",date.strftime("%m")].join %></td>
              </tr>
            </table>
            <% end %>
          </div> 
        </div>

        <div id="blog_posts">
          <% @blogpost_array.sort.reverse.each do |blogpost| %>
          <p class="blog_title"><%= link_to blogpost.title, blogpost %></p>
          <p class="blog_date"><%= blogpost.created_at.strftime("%d %b. %Y") %></p>
          <div class="blog_content"><%= dat_markdown sentence_truncate(blogpost.content, :sentences => 1) %></div>
          <div class="redbutton"><%= link_to 'Read more', blogpost %>
          </div>
          <% end%>
          <%= will_paginate @blogpost_array, :inner_window => 2, :outer_window => -1, :renderer => PaginationHelper::LinkRenderer %>
          </div>
        </div>
      </div>
    </div>

<!--      <div id="blog_right">    
      </div> -->

    <%= render 'layouts/bottombox' %> 
 
  </div>
  <%= render 'layouts/blogfooter' %>
</div>

app/views/blogposts/_form.html.erb
<%= form_for(@blogpost) do |f| %>
  <% if @blogpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blogpost.errors.count, "error") %> prohibited this blogpost from being saved:</h2>

      <ul id="error_list">
      <% @blogpost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogposts/admin_index.html.erb
<% provide(:title, 'Edit blog') %>
<h1>Edit blog</h1>
<p>When adding a new blogpost or editing an existing one, here's what you have to do:</p>
<p>Just paste or write your text. Don't worry about HTML, except when adding an image or a video. In that case, wrap it in a div with a class of "blog_embed", and specify your desired width and height. For example:</p>
<p>&lt;div class="blog_embed"&gt;</br>
  &lt;img width="250" height="300" src="blah.jpg" alt="Blah" /&gt;</br>
  &lt;/div&gt;</p>
<p><%= link_to 'Create a new Blogpost', new_blogpost_path %></p>

<table style="margin-top: 15px;">
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blogposts.each do |blogpost| %>
  <tr>
    <td><%= link_to blogpost.title, blogpost %></td>
    <td><%= dat_markdown sentence_truncate(blogpost.content, :sentences => 1) %></td>
    <td><%= blogpost.created_at.strftime("%d %b. %Y %H:%M") %></td>
    <td><%= link_to 'Edit', edit_blogpost_path(blogpost) %></td>
    <td><%= link_to 'Destroy', blogpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/blogposts/edit.html.erb
<h1>Editing blogpost</h1>

<%= render 'form' %>

<%= link_to 'Show', @blogpost %> |
<%= link_to 'Back', '/blog-admin' %>

app/views/blogposts/index.html.erb
<% provide(:title, 'News') %>
<div id="header_container">
     <div id="wrapper">
        <div id="header">

          <div id="logo">
            <%= link_to image_tag("bear-archery-products-logo.gif", id:"logo", alt:"Bearshotgun"), '/' %>
          </div>
            <ul id="nav">
              <li><a class="upper" href="#"><span style="color: #DA5252;">News</span></a></li>
              <li><a class="upper" href="/our-work/a-game-of-zolf">Our Work</a>
            </li>
              <li><a class="upper" href="/about/company-info">About us</a>
            </li>
              <li><a class="upper" href="/contact">Contact</a></li>
            </ul>

<%= render 'layouts/subpageheader' %>

<div id= "wrapper">
  <div id= "body_container" style="height: auto; float: left;">
    <div style="margin-top:-240px;">
      <img src="/assets/Rovio_subpagebanner_6.jpg" alt:"Welcome to Bearshotgun!" style="border-top-left-radius: 15px; border-top-right-radius: 15px; width: 980px; height: 240px;" />
    </div>
    <div id="subpagepicbox" style="margin-left: 140px; width: 103px;">
    </div>
    <img id="subpagepic" style="margin-left: 140px;" src="/assets/News.png" alt:"News" /> 

    <div>
      <div id="container-outer">
        <div id="container-inner">

        <div id="blog_archive">
          <div id="archive_box"> 
            <% @blogpost_by_month.sort.reverse.each do |date, blogposts| %>
            <p class="blog_year"><%= date.strftime("%Y") %></p>
            <table>
              <tr>
                <td><a class="blog_month" href="<%= ["/archive/",date.strftime("%Y"),"/",date.strftime("%m")].join %>"><%= date.strftime("%B") %></td><td class="blog_amount"><%= link_to [("("),blogposts.count,(")")].join, ["/archive/",date.strftime("%Y"),"/",date.strftime("%m")].join %></td>
              </tr>
            </table>
            <% end %>
          </div> 
        </div>

        <div id="blog_posts">
          <% @blogposts.each do |blogpost| %>

          <p class="blog_title"><%= link_to blogpost.title, blogpost %></p>
          <p class="blog_date"><%= blogpost.created_at.strftime("%d %b. %Y") %></p>
          <div class="blog_content"><%= dat_markdown sentence_truncate(blogpost.content, :sentences => 1) %>
          </div>
          <div class="redbutton"><%= link_to 'Read more', blogpost %>
          </div>
          <% end %>
          <%= will_paginate @blogposts, :inner_window => 2, :outer_window => -1, :renderer => PaginationHelper::LinkRenderer %>
        </div> 

        </div>
      </div>
    </div>
<!--        <div id="blog_right">    
        </div> -->




    <%= render 'layouts/bottombox' %> 
 
  </div>
  <%= render 'layouts/blogfooter' %>
</div>

app/views/blogposts/new.html.erb
<h1>New blogpost</h1>

<%= render 'form' %>

<%= link_to 'Back', '/blog-admin' %>

app/views/blogposts/show.html.erb
<% provide(:title, 'News') %>
<div id="header_container">
     <div id="wrapper">
        <div id="header">

          <div id="logo">
            <%= link_to image_tag("bear-archery-products-logo.gif", id:"logo", alt:"Bearshotgun"), '/' %>
          </div>
            <ul id="nav">
              <li><a class="upper" href="/blog"><span style="color: #DA5252;">News</span></a></li>
              <li><a class="upper" href="/our-work/a-game-of-zolf">Our Work</a>
            </li>
              <li><a class="upper" href="/about/company-info">About us</a>
            </li>
              <li><a class="upper" href="/contact">Contact</a></li>
            </ul>

<%= render 'layouts/subpageheader' %>

<div id= "wrapper">
  <div id= "body_container" style="height: auto; float: left;">
    <div style="margin-top:-240px;">
      <img src="/assets/Rovio_subpagebanner_6.jpg" alt:"Welcome to Bearshotgun!" style="border-top-left-radius: 15px; border-top-right-radius: 15px; width: 980px; height: 240px;" />
    </div>
    <div id="subpagepicbox" style="margin-left: 140px; width: 103px;">
    </div>
    <img id="subpagepic" style="margin-left: 140px;" src="/assets/News.png" alt:"News" /> 

    <div>
      <div id="container-outer">
        <div id="container-inner">

        <div id="blog_archive">
          <div id="archive_box">
            <% @blogpost_by_month.sort.reverse.each do |date, blogposts| %>
            <p class="blog_year"><%= date.strftime("%Y") %></p>
            <table>
              <tr>
                <td><a style="text-decoration: none; outline: none;" href="<%= ["/archive/",date.strftime("%Y"),"/",date.strftime("%m")].join %>"><p class="blog_month"><%= date.strftime("%B") %></p></a></td><td class="blog_amount"><%= link_to [("("),blogposts.count,(")")].join, ["/archive/",date.strftime("%Y"),"/",date.strftime("%m")].join %></td>
              </tr>
            </table>
            <% end %>
          </div> 
        </div>

        <div id="blog_posts">

          <p class="blog_title"><%= @blogpost.title %></p>
          <p class="blog_date"><%= @blogpost.created_at.strftime("%d %b. %Y") %></p>
          <div class="blog_content" style="margin-top: 15px;"><%= dat_markdown (@blogpost.content) %>
          </div>
          <div class="redbutton" style="width: 16%; margin-top: 25px; margin-bottom: 25px;"><%= link_to 'Back to list', blog_path %>
          </div>
        </div>   

        </div>
      </div>
    </div>

<!--    <div id="blog_right">    
    </div>  -->

    <%= render 'layouts/bottombox' %> 

  </div>
  <%= render 'layouts/blogfooter' %>
</div>

app/views/contact/new.html.erb
<% provide(:title, 'Contact Us') %>
<div id="header_container">
     <div id="wrapper">
        <div id="header">

          <div id="logo">
            <%= link_to image_tag("bear-archery-products-logo.gif", id:"logo", alt:"Bearshotgun"), '/' %>
          </div>
            <ul id="nav">
              <li><a class="upper" href="/blog">News</a></li>
              <li><a class="upper" href="/our-work/a-game-of-zolf">Our Work</a>
            </li>
              <li><a class="upper" href="/about/company-info">About us</a>
            </li>
              <li><a class="upper" href="#"><span style="color: #DA5252;">Contact</span></a></li>
            </ul>

<%= render 'layouts/subpageheader' %>

<div id="wrapper">
  <div id="body_container" style="height: 765px;">
    <div style="margin-top:-240px;">
      <img src="/assets/Rovio_subpagebanner_6.jpg" alt:"Welcome to Bearshotgun!" style="border-top-left-radius: 15px; border-top-right-radius: 15px; width: 980px; height: 240px;" />
    </div>
    <div id="subpagepicbox" style="width: 185px;">
    </div>
    <img id="subpagepic" src="/assets/Contact Us.png" alt:"Contact Us" />
    <div id="body_top_l">
    </div>
    <div id="body_top_r" style="margin-left:270px; width: 710px;">
    </div>
    <div id="body_box2" style="height: 580px;">
      <div id="subpagecontentbox" style="height: 625px;">
<!--        <%= image_tag("bear-archery-products-logo.gif", id:"contact_pic", alt:"Bearshotgun") %> -->
        <p><span style="font-size: 15pt; letter-spacing: -2px;">THANKS FOR STOPPING BY!</span></p>
        <p id="subpagetextbox">This is where you can get in touch with us.</p>
        <p id="subpagetextbox">Please fill in the form below, and we'll get back to you as soon as humanly possible, by any means necessary.<p>

        <%= form_for @message, :url => contact_path do |form| %>
        <% if @message.errors.any? %>
          <div id="error_explanation">
            <p style="margin-top:-8px; font-weight: bold"><%= pluralize(@message.errors.count, "error") %> prohibited this message from being sent:</p>
            <ul id="error_list">
              <% @message.errors.each do |attr, msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <table id="contact_table">
          <tr>
            <th id="contact_description"><%= form.label :firstname, "First Name" %> </th>
            <td id="contact_field1"><%= form.text_field :firstname %></td>
          </tr>
          <tr>
            <th id="contact_description"><%= form.label :lastname, "Last Name" %> </th>
            <td id="contact_field1"><%= form.text_field :lastname %></td>
          </tr>
          <tr>
            <th id="contact_description"><%= form.label :email, "E-mail" %> </th>
            <td id="contact_field1"><%= form.text_field :email %></td>
          </tr>
          <tr>
            <th id="contact_description" style="position: absolute; margin-top: 15px;"><%= form.label :company %><span style="font-weight: lighter;"> (optional)</span></th>
            <td id="contact_field1"><%= form.text_field :company %></td>
          </tr>
          <tr>
            <th id="contact_description"><%= form.label :phone %><span style="font-weight: lighter;"> (optional)</span></th>
            <td id="contact_field1"><%= form.text_field :phone %></td>
          </tr>
          <tr>
            <th id="contact_description" style="position: absolute; margin-top: 25px;"><%= form.label :body, "Your Message" %> </th>
            <td id="contact_field1"><%= form.text_area :body, :rows => 5, :cols => 0 %></td>
          </tr>
        </table>
        <div id="submit">
          <%= form.submit "Submit", class: "contactbutton" %>
        <% end %>
      </div>
      </div>
    </div>
    <div id="body_bottom_l"></div>
    <div id="body_bottom_r"></div>
    <%= render 'layouts/bottombox' %>
  </div>
</div>
<%= render 'layouts/footer' %>

app/views/layouts/_bottombox.html.erb
<div id="bottom_box" style="float: left;">

	  	<div id="column_footer_1">
	    <div class="footer_text_box">
	      <ul class="footer_list">
			<li><span style="color: #000000; text-transform: uppercase; font-size: 10pt;">Bearshotgun Games</span>
		  		<ul class="footer_list_nested" style="margin-top: 5px;">
		    		<li>The Salisbury</li>
		    		<li>5th Floor (744-750)</li>
		    		<li>London, EC2M 5QQ</li>
		    		<li>United Kingdom</li>
		  		</ul> 
			</li>
	      </ul>
        </div>
	  	</div>
	  	<div id="column_footer_2">
	    <div class="footer_text_box">
	      <ul class="footer_list">
			<li><a href="/blog"><span style="text-transform: uppercase; font-size: 10pt;">News</span></a>
		  		<ul class="footer_list_nested">
		    		<li><a href="/blog">Blog</a></li>
		    		<li><a href="#">Follow us on Twitter</a></li>
		  		</ul>
			</li>
	      </ul>
        </div>
	  	</div>
	  	<div id="column_footer_3">
	    <div class="footer_text_box">
	      <ul class="footer_list">
			<li><a href="/our-work/a-game-of-zolf"><span style="text-transform: uppercase; font-size: 10pt;">Our Work</span></a>
		  		<ul class="footer_list_nested">
		    		<li><a href="/our-work/a-game-of-zolf">A Game of Zolf</a></li>
		    		<li><a href="/our-work/misfortune-cookie-box">Misfortune Cookie Box</a></li>
		    		<li><a href="/our-work/app-development">App development</a></li>
		  		</ul>
			</li>
	      </ul>
        </div>
	  	</div>
	  	<div id="column_footer_4">
	    <div class="footer_text_box">
	      <ul class="footer_list">
			<li><a href="/about/company-info"><span style="text-transform: uppercase; font-size: 10pt;">About Us</span></a>
		  		<ul class="footer_list_nested">
		    		<li><a href="/about/company-info">Company Info</a></li>
		    		<li><a href="#">Press kit</a></li>
		  		</ul>
			</li>
	      </ul>
        </div>
	  	</div>
	  	<div id="column_footer_5">
	    <div class="footer_text_box">
	      <ul class="footer_list">
			<li><a href="/contact"><span style="text-transform: uppercase; font-size: 10pt;">Contact</span></a>
			</li>
	      </ul>
        </div>
	  	</div>
	  
	  </div>

app/views/layouts/_footer.html.erb
<div id="footer_container">
	<div id="wrapper">
  		<div id="footer">&copy;2012 Bearshotgun Software Ltd. A Game of Zolf.</div>
  	</div>
</div>

app/views/layouts/_notice_div.html.erb
<% if flash[:notice] %>
	<p id="notice"><%= flash[:notice] %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><%=yield(:title) %> | Bearshotgun Games Ltd</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <script language="JavaScript" type="text/javascript">
    pic1= new Image(); 
    pic1.src="/assets/bear-archery-products-logo.gif";
    pic2= new Image(); 
    pic2.src="/assets/logo3.jpg";
    pic3= new Image(); 
    pic3.src="/assets/Misfortuneicon.png";
    pic4= new Image(); 
    pic4.src="/assets/logo2.jpg";  
   </script>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class = "container">
		<%= yield %>
	</div>
<%= javascript_include_tag "application" %>
</body>
</html>